In [3]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5,6,7])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [11]:
#indexing

In [13]:
arr[0]

1

In [15]:
arr[3]

4

In [17]:
arr2[0,2]

3

In [19]:
arr2[1,2]

6

In [25]:
arr3[0,1,3]

8

In [27]:
arr3[1,1,1]

14

In [33]:
#slicing

In [39]:
arr = np.array([1,2,3,4,5,6,7])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [43]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [45]:
arr2[0,0:2]

array([1, 2])

In [47]:
arr3[1,0,0:3]

array([ 9, 10, 11])

In [49]:
arr = np.array([[[1,3,4,5],[6,7,8,9]],[[10,11,12,13],[14,15,16,17]]], dtype = 'S')

In [51]:
arr

array([[[b'1', b'3', b'4', b'5'],
        [b'6', b'7', b'8', b'9']],

       [[b'10', b'11', b'12', b'13'],
        [b'14', b'15', b'16', b'17']]], dtype='|S2')

In [62]:
arr = np.array([1,2,3,4,5,6,7], ndmin = 5)

In [64]:
arr.ndim

5

In [70]:
a = ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b = ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

arr = np.concatenate((a, b), axis = 1)

In [72]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
print(a)
print(b)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [78]:
#split

In [84]:
a = np.array([1,2,3,4,5,6,7,8])
arr = np.array_split(a,3)

In [86]:
arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [88]:
#ravel and flatten

In [94]:
m = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
n = m.flatten()

print(m)
print(n)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [96]:
#Unique Function

In [108]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
[ 1  2  3  4  5  6  7  9 12 22 33]


In [110]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True)   #index positon to see
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64))


In [112]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True, return_counts = True) #which number have 2 time in array
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64), array([2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1], dtype=int64))


In [114]:
# Delete Function

In [116]:
a = ([1,2,3,4])
d = np.delete(a, 0)
d

array([2, 3, 4])

In [122]:
a = ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d = np.delete(a, 1, axis = 1)

In [124]:
d

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [126]:
# some basic function on numpy

In [128]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("No. of dimension: ", arr.ndim)
print("shape of array: ", arr.shape)
print("size of array: ", arr.size)
print("Array stores elements in bytes: ", arr.dtype)
print("length of one array element in bytes: ", arr.itemsize)
print("array's data ", arr.data)

No. of dimension:  3
shape of array:  (2, 2, 3)
size of array:  12
Array stores elements in bytes:  int32
length of one array element in bytes:  4
array's data  <memory at 0x000002451558BE20>


In [130]:
#reshape

a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
